### ISSUE TITLE
November 2018 Preservation Catalog Update

### ISSUE THREAD

**Issue by mcohenui** [NeighborhoodInfoDC/PresCat#177]
_If you have not previously done so, [clone the PresCat repo](https://help.github.com/desktop/guides/contributing-to-projects/cloning-a-repository-from-github-to-github-desktop/) to **D:\DCData\Libraries** before proceeding._
_Make sure you complete the HUD and DHCD updates for this month before starting on this issue._

_**Run updates**_
- [ ] [Create new branch](https://help.github.com/desktop/guides/contributing-to-projects/creating-a-branch-for-your-work/) **update-#**_n_ in GitHub Desktop for work on this issue (where _n_=issue number). 
- [ ] [Update Preservation Catalog with Sec8MF data](https://urbanorg.app.box.com/notes/45544495689)
- [ ] [Update Preservation Catalog with MFIS data](https://urbanorg.app.box.com/notes/48593611845)
- [ ] [Update Preservation Catalog with REAC data](https://urbanorg.app.box.com/notes/317426216726)
- [ ] [Request review and finalize programs](https://urbanorg.app.box.com/notes/295752223069)
- [ ] After code has been reviewed and approved, **merge branch, sync to L:, and batch submit** all programs updated above.
- [ ] Batch submit **L:\Libraries\PresCat\Prog\Updates\Update_real_property.sas**
- [ ] Batch submit **L:\Libraries\Metadata\Prog\DC_CREATE_META_HTML_local.sas** to update the metadata pages.

_**Run and review reports**_
- [ ] Batch submit **L:\Libraries\PresCat\Prog\Reports\Expiration_rpt.sas**
  - [ ] Review the report output, **L:\Libraries\PresCat\Prog\Reports\Expiration_rpt_yyyymmdd.xls**, which will have the current date (_yyyymmdd_) in the file name. Add projects with expiring subsidies to the Preservation Network meeting agenda section B and [change the Catalog Category](https://urbanorg.app.box.com/notes/45548238609) to 2 (expiring subsidy). 
- [ ] Batch submit **L:\Libraries\PresCat\Prog\Reports\Real_property_rpt.sas**
  - [ ] Review the report output, **L:\Libraries\PresCat\Prog\Reports\Real_property_rpt_yyyymmdd.xls**, which will have the current date (_yyyymmdd_) in the file name. Add new notices to the Preservation Network meeting agenda. In some cases, this may mean adding a project to the agenda and [changing the Catalog Category](https://urbanorg.app.box.com/notes/45548238609) to 4 (more information needed). 

_**Finalize monthly meeting agenda and Catalog PDF**_
- [ ] Review the output files from each of the updates run above. This includes
  - Update_Sec8mf_yyyy_mm_subsidy.pdf 
  - Update_Sec8mf_yyyy_mm_project.pdf
  - Update_MFIS_yyyy_mm_subsidy.pdf 
  - Update_MFIS_yyyy_mm_project.pdf
  - [ ] Add info about latest updates (new expiration dates, ownership changes, etc.) to Preservation Network meeting agenda
- [ ] Make final changes to [Category variable](https://urbanorg.app.box.com/notes/45548238609) to move projects to different sections of the Preservation Catalog (if needed). 
- [ ] Create the [Catalog PDF report](https://urbanorg.app.box.com/notes/45624463637)
- [ ] Send **updated agenda** and **Catalog PDF** to CNHED

_**Update web site**_
- [ ] [Update Preservation Catalog web site](https://urbanorg.app.box.com/notes/295939490660)

_Do not close this issue until **all** the steps above have been completed._

**Comment by ptatian** [comment]
@mcohenui @Woliver01 As part of this upcoming update, please make a manual edit to the Subsidy exception file (Subsidy_except) for project NL000262 (Sayles Place). I heard from DHCD that HUD said all of the federal subsidies on this project are now gone. 

We should edit the exception data set (Subsidy_except) to flag the two HUD subsidies as inactive. Use this program to edit the data set. 

L:\Libraries\PresCat\Prog\Updates\Edit_subsidy_except.sas

Instructions are in the program header. 

There are two HUD subsidies, **Sec 236(j)(1)/Lower Income Families** and **Sec 8 loan management set-aside**. You will need to add records for the two subsidies to the exception data set, so you should first check what Subsidy_id is associated with the two subsidies in PresCat.Subsidy. The only info you need on each record is **nlihc_id, subsidy_id, subsidy_active, except_init, and except_date**. All other fields can be left blank (missing). Subsidy_active should be set to 0. Except_init is the initials of the person entering the record. Except_date is the date when the entry was made, which needs to be entered as a SAS date value (ie, number of days since 1/1/1960). You can use this [date value calculator](https://www.sastipsbyhal.com/2012/01/sas-date-calculator-now-available.html) to find the right value. 

This should be done before you run any other updates. 

Please let me know if you have any questions. Thank you!
